"""
give some data to help figure out the CSE time complexity.
the log files should be generated by crc-perftest.ps1.

idk if the data is useful, and also it really depends on
if there are enough datapoints.

requires numpy and pandas.
"""

import numpy  as np
import pandas as pd
from glob import glob
import json

def get_r2(x, y):
	m, b = np.polyfit(x, y, 1)

	y_pred = m*x + b

	ss_res = np.sum((y - y_pred)**2)
	ss_tot = np.sum((y - np.mean(y))**2)

	return 1 - ss_res / ss_tot

for logfile in glob("./perflogs/*.log"):
	alg = logfile[11:-4]
	df = pd.read_csv(logfile, sep=r"\s+")

	n = df.data_len.to_numpy()
	T = df.cse_time_ns.to_numpy()

	logn = np.log2(n)
	logT = np.log2(T)

	results = [
		("deg1"   , get_r2(n, T)),
		("deg2"   , get_r2(n**2, T)),
		("deg3"   , get_r2(n**3, T)),
		("deg4"   , get_r2(n**4, T)),
		("deg5"   , get_r2(n**5, T)),
		("n1 logn", get_r2(n*logn, T)),
		("n2 logn", get_r2(n**2*logn, T)),
		("n3 logn", get_r2(n**3*logn, T)),
		("n4 logn", get_r2(n**4*logn, T)),
		("n5 logn", get_r2(n**5*logn, T)),
		("log"    , get_r2(logn, T)),
		("exp"    , get_r2(n, logT)),
		("poly"   , get_r2(logn, logT)),
	]
	results = dict(sorted(results, key=lambda x: x[1], reverse=True))

	alpha = np.log2(T[1:] / T[:-1])

	print(f"{alg}:", json.dumps(results, indent='\t'))
	print(f"alpha = {alpha.tolist()}", end="\n\n")
